#include "pch.h"
#include "CPlayerState.h"

#include "CResMgr.h"

#include "CPlayerStandLeft.h"
#include "CPlayerStandRight.h"
#include "CPlayerWalkLeft.h"
#include "CPlayerWalkRight.h"
#include "CPlayerProneLeft.h"
#include "CPlayerProneRight.h"
#include "CPlayerJumpLeft.h"
#include "CPlayerJumpRight.h"
#include "CPlayerRope.h"
#include "CPlayerLadder.h"
#include "CPlayerAlertLeft.h"
#include "CPlayerAlertRight.h"

#include "CPlayerSkillStroke.h"
#include "CPlayerSkillStroke2.h"
#include "CPlayerSkillShotgun1.h"
#include "CPlayerSkillShotgun2.h"
#include "CPlayerSkillShotgun3.h"
#include "CPlayerSkillBrick1.h"
#include "CPlayerSkillBrick2.h"
#include "CPlayerSkillBrick3.h"
#include "CPlayerSkillBrick4.h"

CPlayerStandLeft CPlayerState::standleft;
CPlayerStandRight CPlayerState::standright;
CPlayerWalkLeft CPlayerState::walkleft;
CPlayerWalkRight CPlayerState::walkright;
CPlayerProneLeft CPlayerState::proneleft;
CPlayerProneRight CPlayerState::proneright;
CPlayerJumpLeft CPlayerState::jumpleft;
CPlayerJumpRight CPlayerState::jumpright;
CPlayerRope CPlayerState::rope;
CPlayerLadder CPlayerState::ladder;
CPlayerSkillStroke CPlayerState::Storke;
CPlayerAlertLeft CPlayerState::alertleft;
CPlayerAlertRight CPlayerState::alertright;
CPlayerSkillStroke2 CPlayerState::Stroke2;
CPlayerSkillShotgun1 CPlayerState::shotgun1;
CPlayerSkillShotgun2 CPlayerState::shotgun2;
CPlayerSkillShotgun3 CPlayerState::shotgun3;
CPlayerSkillBrick1 CPlayerState::brick1;
CPlayerSkillBrick2 CPlayerState::brick2;
CPlayerSkillBrick3 CPlayerState::brick3;
CPlayerSkillBrick4 CPlayerState::brick4;